--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 15.8

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA "public";


--
-- Name: SCHEMA "public"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA "public" IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = "heap";

--
-- Name: continue_watching; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."continue_watching" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "episode_id" "text" NOT NULL,
    "progress_seconds" integer,
    "last_watched_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


--
-- Name: episodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."episodes" (
    "id" "text" NOT NULL,
    "series_id" "text" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "episode_number" integer,
    "season_number" integer,
    "video_url_hls" "text",
    "video_url_mp4" "text",
    "thumbnail_url" "text",
    "duration_seconds" integer,
    "release_date" "date",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


--
-- Name: persona; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."persona" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text"
);


--
-- Name: persona_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE "public"."persona" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."persona_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."profiles" (
    "id" "uuid" NOT NULL,
    "username" "text",
    "full_name" "text",
    "avatar_url" "text",
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


--
-- Name: series; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE "public"."series" (
    "id" "text" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "cover_image_url" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


--
-- Name: continue_watching continue_watching_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."continue_watching"
    ADD CONSTRAINT "continue_watching_pkey" PRIMARY KEY ("id");


--
-- Name: episodes episodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."episodes"
    ADD CONSTRAINT "episodes_pkey" PRIMARY KEY ("id");


--
-- Name: persona persona_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."persona"
    ADD CONSTRAINT "persona_pkey" PRIMARY KEY ("id");


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");


--
-- Name: profiles profiles_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_username_key" UNIQUE ("username");


--
-- Name: series series_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."series"
    ADD CONSTRAINT "series_pkey" PRIMARY KEY ("id");


--
-- Name: continue_watching user_episode_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."continue_watching"
    ADD CONSTRAINT "user_episode_unique" UNIQUE ("user_id", "episode_id");


--
-- Name: idx_continue_watching_user_episode; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_continue_watching_user_episode" ON "public"."continue_watching" USING "btree" ("user_id", "episode_id");


--
-- Name: idx_episodes_series_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "idx_episodes_series_id" ON "public"."episodes" USING "btree" ("series_id");


--
-- Name: profiles fk_auth_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "fk_auth_user" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;


--
-- Name: continue_watching fk_auth_user_progress; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."continue_watching"
    ADD CONSTRAINT "fk_auth_user_progress" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;


--
-- Name: continue_watching fk_episode_progress; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."continue_watching"
    ADD CONSTRAINT "fk_episode_progress" FOREIGN KEY ("episode_id") REFERENCES "public"."episodes"("id") ON DELETE CASCADE;


--
-- Name: episodes fk_series; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY "public"."episodes"
    ADD CONSTRAINT "fk_series" FOREIGN KEY ("series_id") REFERENCES "public"."series"("id") ON DELETE CASCADE;


--
-- Name: episodes Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON "public"."episodes" FOR SELECT TO "anon" USING (true);


--
-- Name: profiles Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON "public"."profiles" FOR SELECT TO "anon" USING (true);


--
-- Name: series Enable read access for all users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Enable read access for all users" ON "public"."series" FOR SELECT TO "anon" USING (true);


--
-- Name: continue_watching; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE "public"."continue_watching" ENABLE ROW LEVEL SECURITY;

--
-- Name: episodes; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE "public"."episodes" ENABLE ROW LEVEL SECURITY;

--
-- Name: persona; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE "public"."persona" ENABLE ROW LEVEL SECURITY;

--
-- Name: profiles; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;

--
-- Name: series; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE "public"."series" ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

